<?php

/* Contains all custom translation keys (not generated by the lang library) */
/* AI generated file - Did it that way to save time */

declare(strict_types=1);

return [
    'home' => [
        'title' => 'Home',
        'description' => 'Home page of the social network.',
        'introduction' => 'Welcome to :app_name!',
    ],
    'profile' => [
        'title' => 'Profile of :username',
        'description' => 'Profile page for :username.',
        'number_of_posts' => '{0} No posts|{1} :count post|[2,*] :count posts',
    ],
    'about' => [
        'title' => 'About',
        'description' => 'About page of our social network.',
        'introduction' => 'This social network was created to allow users to share their thoughts and ideas with the whole world.',
        'disclaimer' => 'This social network is a project made as part of a course at HEIG-VD, Switzerland.',
        'copyright' => '© :year All rights reserved.',
    ],
    'errors' => [
        '404' => [
            'title' => 'Page not found',
            'description' => 'The page you are looking for does not exist.',
            'heading' => 'Page not found',
            'message' => 'Sorry, the page you are looking for does not exist or has been moved.',
            'back_home' => 'Back to home',
        ],
    ],
    'posts' => [
        'no_posts' => 'No posts to display.',
        'likes_count' => '{0} No likes|{1} :count like|[2,*] :count likes',
    ],
];
